question_data = [{"category": "Entertainment: Video Games",
                  "difficulty": "easy",
                  "question": "The main character in the Half-Life franchise is named Morgan Freeman.",
                  "correct_answer": "False"},
                 {"category": "Geography",
                  "difficulty": "medium",
                  "question": "The flag of South Africa features 7 colours.",
                  "correct_answer": "False"},
                 {"category": "Entertainment: Music", "difficulty": "medium",
                  "question": "Rapper Snoop Doggs real name is Cordozar Calvin Broadus, Jr..",
                  "correct_answer": "True"},
                 {"category": "General Knowledge", "difficulty": "medium",
                  "question": "Coca-Colas original colour was green.", "correct_answer": "False"},
                 {"category": "Entertainment: Film", "difficulty": "medium",
                  "question": "There arent any live-action clones in Star Wars: Episode III - Revenge of the Sith.",
                  "correct_answer": "True"},
                 {"category": "Entertainment: Video Games", "difficulty": "easy",
                  "question": "In Super Mario 64, collecting 100 coins on a level will give you a 1-UP.",
                  "correct_answer": "False"},
                 {"category": "Animals", "difficulty": "medium",
                  "question": "Kamea, the Gilbertese Islander word for dog, is derived from the English phrase Come here!",
                  "correct_answer": "True"},
                 {"category": "Politics", "difficulty": "easy",
                  "question": "In 2016, the United Kingdom voted to stay in the EU.",
                  "correct_answer": "False"},
                 {"category": "History", "difficulty": "medium",
                  "question": "Brezhnev was the 5th leader of the USSR.", "correct_answer": "True"},
                 {"category": "Entertainment: Video Games", "difficulty": "easy",
                  "question": "In Super Mario Bros., the clouds and bushes have the same artwork and are just different colors.",
                  "correct_answer": "True"},
                 {"category": "General Knowledge", "difficulty": "medium",
                  "question": "The bikini is named after the Bikini Atoll, an island where the United States conducted tests on atomic bombs.",
                  "correct_answer": "True"},
                 {"category": "Entertainment: Japanese Anime & Manga",
                  "difficulty": "easy",
                  "question": "The anime Lucky Star follows the story of one girl who is unaware she is God.",
                  "correct_answer": "False"},
                 {"category": "Entertainment: Video Games", "difficulty": "easy",
                  "question": "Tetris is the #1 best-selling video game of all-time.",
                  "correct_answer": "False"},
                 {"category": "Entertainment: Video Games", "difficulty": "easy",
                  "question": "Solid Snake is actually a clone from the DNA of Big Boss in the Metal Gear Solid series history.",
                  "correct_answer": "True"},
                 {"category": "General Knowledge", "difficulty": "medium",
                  "question": "The term Spam came before the food product Spam.",
                  "correct_answer": "False"},
                 {"category": "Entertainment: Video Games", "difficulty": "easy",
                  "question": "Deus Ex (2000) does not feature the World Trade Center because it was destroyed by terrorist attacks according to the games plot.",
                  "correct_answer": "True"},
                 {"category": "Mythology", "difficulty": "medium",
                  "question": "The Japanese god Izanagi successfully returned his wife Izanami from the Underworld.",
                  "correct_answer": "False"},
                 {"category": "Entertainment: Video Games", "difficulty": "medium",
                  "question": "TF2: The Medic will be credited for an assist if he heals a Spy that successfully saps a building.",
                  "correct_answer": "True"},
                 {"category": "Entertainment: Video Games", "difficulty": "medium",
                  "question": "TF2: The Heavys voice actor, Gary Schwartz, voices the Demoman as well ",
                  "correct_answer": "True"},
                 {"category": "Sports", "difficulty": "medium",
                  "question": "The Olympics tennis court is a giant green screen.",
                  "correct_answer": "True"},
                 {"category": "Entertainment: Japanese Anime & Manga",
                  "difficulty": "hard",
                  "question": "Throughout the entirety of Dragon Ball Z, Goku only kills two characters: a miniboss named Yakon and Kid Buu.",
                  "correct_answer": "True"},
                 {"category": "General Knowledge", "difficulty": "easy",
                  "question": "Adolf Hitler was born in Australia. ", "correct_answer": "False"},
                 {"category": "Entertainment: Film", "difficulty": "easy",
                  "question": "In the original Star Wars trilogy, Alec Guinness provided the voice for Darth Vader.",
                  "correct_answer": "False"},
                 {"category": "Entertainment: Music", "difficulty": "hard",
                  "question": "The song Mystery Train was released by artist Little Juniors Blue Flames in 1953.",
                  "correct_answer": "True"},
                 {"category": "Science: Gadgets", "difficulty": "easy",
                  "question": "Microphones can be used not only to pick up sound, but also to project sound similar to a speaker.",
                  "correct_answer": "True"},
                 {"category": "Science: Computers", "difficulty": "easy",
                  "question": "The Windows ME operating system was released in the year 2000.",
                  "correct_answer": "True"},
                 {"category": "Entertainment: Music", "difficulty": "easy",
                  "question": "A Saxophone is a brass instrument.", "correct_answer": "False"},
                 {"category": "Science: Mathematics", "difficulty": "medium",
                  "question": "E = MC3", "correct_answer": "False"},
                 {"category": "History", "difficulty": "medium",
                  "question": "Martin Luther King Jr. and Anne Frank were born the same year. ",
                  "correct_answer": "True"},
                 {"category": "Entertainment: Video Games", "difficulty": "medium",
                  "question": "In Rocket League, you can play Basketball.", "correct_answer": "True"},
                 {"category": "Politics", "difficulty": "medium",
                  "question": "The State of Queensland, Australia voted NO to a referendum for daylight savings in 1992.",
                  "correct_answer": "True"},
                 {"category": "Science: Mathematics", "difficulty": "medium",
                  "question": "A Millinillion is a real number.", "correct_answer": "True"},
                 {"category": "Entertainment: Video Games", "difficulty": "easy",
                  "question": "Watch_Dogs 2 is a prequel.", "correct_answer": "False"},
                 {"category": "Entertainment: Japanese Anime & Manga",
                  "difficulty": "hard", "question": "Druid is a mage class in Log Horizon.",
                  "correct_answer": "False"},
                 {"category": "Entertainment: Board Games", "difficulty": "hard",
                  "question": "The board game Go has more possible legal positions than the number of atoms in the visible universe.",
                  "correct_answer": "True"},
                 {"category": "Entertainment: Television", "difficulty": "easy",
                  "question": "In Star Trek, Klaang is a typical Klingon male.",
                  "correct_answer": "True"},
                 {"category": "Science: Mathematics", "difficulty": "hard",
                  "question": "In Topology, the complement of an open set is a closed set.",
                  "correct_answer": "True"},
                 {"category": "Science: Mathematics", "difficulty": "medium",
                  "question": "The set of all algebraic numbers is countable.",
                  "correct_answer": "True"},
                 {"category": "Entertainment: Video Games", "difficulty": "medium",
                  "question": "Return to Castle Wolfenstein was the only game of the Wolfenstein series where you dont play as William B.J. Blazkowicz.",
                  "correct_answer": "False"},
                 {"category": "Entertainment: Video Games", "difficulty": "medium",
                  "question": "The character that would eventually become Dr. Eggman was considered for the role of Segas new flagship mascot before Sonic was.",
                  "correct_answer": "True"},
                 {"category": "Entertainment: Video Games", "difficulty": "easy",
                  "question": "Sonic the Hedgehog 2 originally was going to have a time travel system.",
                  "correct_answer": "True"},
                 {"category": "Mythology", "difficulty": "hard",
                  "question": "Janus was the Roman god of doorways and passageways.",
                  "correct_answer": "True"},
                 {"category": "Animals", "difficulty": "medium",
                  "question": "Tigers have one colour of skin despite the stripey fur.",
                  "correct_answer": "False"},
                 {"category": "Entertainment: Music", "difficulty": "hard",
                  "question": "The singer Billie Holiday was also known as Lady Day.",
                  "correct_answer": "True"},
                 {"category": "General Knowledge", "difficulty": "medium",
                  "question": "The British organisation CAMRA stands for The Campaign for Real Ale.",
                  "correct_answer": "True"},
                 {"category": "Entertainment: Music", "difficulty": "medium",
                  "question": "Metallica collaborated with Rowan Atkinsons Mr Bean on a 1992 comic relief single.",
                  "correct_answer": "False"},
                 {"category": "Entertainment: Video Games", "difficulty": "medium",
                  "question": "During pre-production of Super Mario Bros., Mario originally was meant to shoot bullets.",
                  "correct_answer": "True"},
                 {"category": "Animals", "difficulty": "easy",
                  "question": "The internet browser Firefox is named after the Red Panda.",
                  "correct_answer": "True"},
                 {"category": "Entertainment: Books", "difficulty": "easy",
                  "question": "The Harry Potter series of books, combined, are over 1,000,000 words in length.",
                  "correct_answer": "True"},
                 {"category": "Entertainment: Books", "difficulty": "easy",
                  "question": "Shub-Niggurath is a creature that was created by \tJ. R. R. Tolkien in his novel The Lord of The Rings.",
                  "correct_answer": "False"}]
